const vietnameseNames = [
    // Tên Unisex (dùng cho cả nam & nữ)
    { name: "An", gender: "Unisex", meaning: "Bình yên, an lành" },
    { name: "Anh", gender: "Unisex", meaning: "Thông minh, sáng sủa" },
    { name: "Bình", gender: "Unisex", meaning: "Hòa bình, yên tĩnh" },
    { name: "Châu", gender: "Unisex", meaning: "Viên ngọc quý" },
    { name: "Khánh", gender: "Unisex", meaning: "Sự vui mừng, phước lành" },
    { name: "Linh", gender: "Unisex", meaning: "Tâm linh, lanh lợi" },
    { name: "Minh", gender: "Unisex", meaning: "Sáng suốt, thông minh" },
    { name: "Ngọc", gender: "Unisex", meaning: "Viên ngọc quý giá" },
    { name: "Thanh", gender: "Unisex", meaning: "Màu xanh, trong sạch" },
    { name: "Tú", gender: "Unisex", meaning: "Thanh tú, tài giỏi" },
    { name: "Xuân", gender: "Unisex", meaning: "Mùa xuân, sức sống mới" },
  
    // Tên Nam
    { name: "Bảo", gender: "Male", meaning: "Bảo bối, quý giá" },
    { name: "Cường", gender: "Male", meaning: "Mạnh mẽ, kiên cường" },
    { name: "Dũng", gender: "Male", meaning: "Dũng cảm, gan dạ" },
    { name: "Đạt", gender: "Male", meaning: "Thành đạt, thành công" },
    { name: "Đức", gender: "Male", meaning: "Đạo đức, nhân từ" },
    { name: "Gia", gender: "Male", meaning: "Gia đình, gia tộc" },
    { name: "Hải", gender: "Male", meaning: "Biển cả, mạnh mẽ" },
    { name: "Hiếu", gender: "Male", meaning: "Hiếu thảo, kính trọng" },
    { name: "Hoàng", gender: "Male", meaning: "Hoàng gia, vàng" },
    { name: "Hùng", gender: "Male", meaning: "Mạnh mẽ, hùng dũng" },
    { name: "Huy", gender: "Male", meaning: "Huy hoàng, rực rỡ" },
    { name: "Khang", gender: "Male", meaning: "Khỏe mạnh, an khang" },
    { name: "Kiên", gender: "Male", meaning: "Kiên trì, bền bỉ" },
    { name: "Lâm", gender: "Male", meaning: "Rừng xanh, mạnh mẽ" },
    { name: "Long", gender: "Male", meaning: "Rồng, quyền lực" },
    { name: "Nhân", gender: "Male", meaning: "Nhân hậu, tốt bụng" },
    { name: "Phát", gender: "Male", meaning: "Phát triển, thành công" },
    { name: "Quân", gender: "Male", meaning: "Quân đội, kỷ luật" },
    { name: "Quang", gender: "Male", meaning: "Hào quang, ánh sáng" },
    { name: "Sơn", gender: "Male", meaning: "Núi, vững chắc" },
    { name: "Thắng", gender: "Male", meaning: "Chiến thắng, thành công" },
    { name: "Thành", gender: "Male", meaning: "Thành đạt, công danh" },
    { name: "Tiến", gender: "Male", meaning: "Tiến bộ, phát triển" },
    { name: "Toàn", gender: "Male", meaning: "Hoàn chỉnh, toàn vẹn" },
    { name: "Tuấn", gender: "Male", meaning: "Khôi ngô, tuấn tú" },
    { name: "Vinh", gender: "Male", meaning: "Vinh quang, danh giá" },
    { name: "Việt", gender: "Male", meaning: "Xuất chúng, người Việt" },
  
    // Tên Nữ
    { name: "Ánh", gender: "Female", meaning: "Ánh sáng, rạng rỡ" },
    { name: "Bích", gender: "Female", meaning: "Ngọc bích, trong sáng" },
    { name: "Diễm", gender: "Female", meaning: "Xinh đẹp, kiều diễm" },
    { name: "Diệu", gender: "Female", meaning: "Huyền diệu, kỳ diệu" },
    { name: "Hạnh", gender: "Female", meaning: "Đức hạnh, tốt đẹp" },
    { name: "Hoa", gender: "Female", meaning: "Bông hoa, sắc đẹp" },
    { name: "Hồng", gender: "Female", meaning: "Màu hồng, rực rỡ" },
    { name: "Huệ", gender: "Female", meaning: "Thanh cao, tinh tế" },
    { name: "Hương", gender: "Female", meaning: "Hương thơm, dịu dàng" },
    { name: "Lan", gender: "Female", meaning: "Hoa lan, tinh khiết" },
    { name: "Liên", gender: "Female", meaning: "Hoa sen, thanh khiết" },
    { name: "Mai", gender: "Female", meaning: "Hoa mai, mùa xuân" },
    { name: "Mỹ", gender: "Female", meaning: "Xinh đẹp, mỹ lệ" },
    { name: "Ngân", gender: "Female", meaning: "Tiền bạc, giàu có" },
    { name: "Ngọc", gender: "Female", meaning: "Ngọc quý, kiêu sa" },
    { name: "Nhung", gender: "Female", meaning: "Mềm mại, sang trọng" },
    { name: "Oanh", gender: "Female", meaning: "Chim oanh, vui vẻ" },
    { name: "Phương", gender: "Female", meaning: "Hương thơm, thông minh" },
    { name: "Quỳnh", gender: "Female", meaning: "Hoa quỳnh, cao quý" },
    { name: "Tâm", gender: "Female", meaning: "Tấm lòng, thiện lương" },
    { name: "Thảo", gender: "Female", meaning: "Cây cỏ, dịu dàng" },
    { name: "Thúy", gender: "Female", meaning: "Mỏng manh, kiều diễm" },
    { name: "Trang", gender: "Female", meaning: "Nghiêm trang, đoan chính" },
    { name: "Tuyết", gender: "Female", meaning: "Màu trắng, trong sáng" },
    { name: "Uyên", gender: "Female", meaning: "Uyên bác, thông minh" },
    { name: "Vân", gender: "Female", meaning: "Mây trời, nhẹ nhàng" },
    { name: "Yến", gender: "Female", meaning: "Chim yến, thanh cao" },
  ];
  
  // Xuất danh sách ra module
  export default vietnameseNames;
  